// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTesting.Data;

namespace WebApiTesting.Migrations
{
    [DbContext(typeof(PockemonContext))]
    [Migration("20210511210704_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiTesting.Model.Pockemo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pockemos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Picachu equis",
                            Name = "picahu Mexicano",
                            Photo = "https://pbs.twimg.com/media/Eio96N9WAAEHuvI.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pelicano equis",
                            Name = "Pelicano Mexicano",
                            Photo = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZpaNtJffGe5VRveyp7akE-mPKOBelV5kkCQ&usqp=CAU"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Perro equis",
                            Name = "Perro Mexicano",
                            Photo = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqTX3pGP591zsndXnabjeEyBQ6L_6m7Frp7w&usqp=CAU"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
